DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS review;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE review (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  creator_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  review TEXT NOT NULL,
  rating INTEGER NOT NULL,
  author TEXT NOT NULL,
  FOREIGN KEY (creator_id) REFERENCES user (id)
);